# Nome do workflow
name: Vercel Staging Deployment

# Variáveis de ambiente para a Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Gatilho: aciona em push para a branch 'homolog'
on:
  push:
    branches:
      - stg

jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala a Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # 5. Faz o deploy para a Vercel e captura a URL de preview
      #    - O comando 'vercel deploy --prebuilt' retorna a URL do deploy.
      #    - 'xargs' é usado para passar essa URL para o próximo passo.
      - name: Deploy to Vercel
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
    